### ISSUE TITLE
Send aprs gps coordinates to a webserver

### ISSUE THREAD

**Issue by inclanfunk** [trasukg/utils-for-aprs#7]
Hello,

My name is Julien, I design a webapp for firefighters to locate them over several map layers based on gprs network. I would like to improve it adding the possibilty to use Aprs protocol. I already have modified handys with Arduino to send gps position over vhf. Now I am looking for a way to convert and send this data over Internet to my server. 
Many thanks for your help

My best,
Julien

**Comment by trasukg** [comment]
Hi Julien:

Unfortunately, I am not very familiar with the internet side of APRS (APRSIS).  I just work with the RF/KISS side of it.  You might find you can use some of the same protocols, though.  There’s more information at http://www.aprs-is.net/

Cheers,

Greg, VA3TSK

**Comment by inclanfunk** [comment]
Thanks, that is what I was looking for.
